version: 2
project_name: flowmi

before:
  hooks:
    - go mod vendor

builds:
  - main: .
    binary: flowmi
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/flowmi/flowmi/cmd.version={{.Version}}
      - -X github.com/flowmi/flowmi/cmd.commit={{.ShortCommit}}
      - -X github.com/flowmi/flowmi/cmd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: flowmi-ai
    name: flowmi
